name: Zip and Upload Artifact

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install zip
      run: sudo apt-get install zip

    - name: Zip files (ignoring specified files)
      run: |
        zip -r archive-${{ github.run_number }}.zip . -x @.zipignore

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: archive-${{ github.run_number }}
        path: archive-${{ github.run_number }}.zip
