name: Zip and Upload Artifact

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create build-info.txt with GitHub context
      run: |
        echo "Run ID: ${{ github.run_id }}" > build-info.txt
        echo "Run Number: ${{ github.run_number }}" >> build-info.txt
        echo "Commit SHA: ${{ github.sha }}" >> build-info.txt
        echo "Repository: ${{ github.repository }} (${{ github.repository_id }})" >> build-info.txt
        echo "Repository URL: ${{ github.repositoryUrl }}" >> build-info.txt
        echo "Triggered by: ${{ github.actor }} (${{ github.actor_id }})" >> build-info.txt

    - name: Install zip
      run: sudo apt-get install zip

    - name: Zip files (ignoring specified files)
      run: |
        zip -r archive-${{ github.run_number }}.zip . -x @.zipignore

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: archive-${{ github.run_number }}
        path: archive-${{ github.run_number }}.zip
